language: cpp
compiler:
  - clang
  - gcc

sudo: required
dist: trusty

install:
  - sudo apt-get install -y libboost-thread1.55-dev libboost-system1.55-dev libboost-filesystem1.55-dev spring
  - cmake -DBUILD_TESTS=ON .
script:
  - make && make check
