#ifndef LIBSPRINGLOBBY_HEADERGUARD_CONFIG_H
#define LIBSPRINGLOBBY_HEADERGUARD_CONFIG_H

#undef VERSION

/* the git tag / commit we build from */
#define VERSION "@LIBSPRINGLOBBY_REV@"

#endif	/* LIBSPRINGLOBBY_HEADERGUARD_CONFIG_H */
